### ISSUE TITLE
如何更改福利金领取次数

### ISSUE THREAD

**Issue by Ble55me** [po-lan/zhenxun_plugins_TZseries#1]
每天5次太刷屏了

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/174939037-9367948d-d136-4298-9cc3-6ab3bf616cc3.png)
安装前可以在这里修改
安装后可以去修改 data/config/下的 次数限制的配置文件
我没写 指令设置 请参考 真寻的文档 进行修改
