### ISSUE TITLE
关于21点功能的建议

### ISSUE THREAD

**Issue by Judp28** [po-lan/zhenxun_plugins_TZseries#14]
有群友开了21点但是没有操作，于是之后的人想开局都会提示上一场还未结束，可以做成5分钟无响应自动关闭吗？还有就是抽牌停牌指令太苛刻了，还要打两个字，如何添加一些指令，比如说抽，停就可以，我尝试添加指令但是报错了，显示不存在该指令

**Comment by Judp28** [comment]
> 指令搞得比较长是为了 防止于别的插件冲突 然后结束的话 超过 90s 超级用户也可以结束

超级用户强制结束的指令是什么，我翻了一下好像没找到，超级用户不在的时候就不能强制结束了吗？如果能像真寻自带的俄罗斯轮盘自动结束就很棒了

**Comment by po-lan** [comment]
> > 指令搞得比较长是为了 防止于别的插件冲突 然后结束的话 超过 90s 超级用户也可以结束
> 
> 超级用户强制结束的指令是什么，我翻了一下好像没找到，超级用户不在的时候就不能强制结束了吗？如果能像真寻自带的俄罗斯轮盘自动结束就很棒了

也是 21点结束
![image](https://user-images.githubusercontent.com/42771836/177661421-d330ce27-129e-42dc-a020-92f79c8effbe.png)

那个东西 我并不会写，我比较擅长js

**Comment by Judp28** [comment]
![Uploading IMG_20220707_075333.png…]()
我尝试这样添加一个抽的指令，但是会报错

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/177661728-39a0cd2a-607e-4bbf-b258-4c27c517a003.png)
我看不见你的图片

**Comment by Judp28** [comment]
我尝试添加一个“抽”的指令，但是会报错
![Uploading IMG_20220707_075333.png…]()

**Comment by Judp28** [comment]
![IMG_20220707_075333](https://user-images.githubusercontent.com/105803689/177661822-910548af-fa3a-48bd-bf7f-b9a1e714819d.png)

**Comment by Judp28** [comment]
我尝试这样添加一个“抽”的指令，但是会报错

**Comment by po-lan** [comment]
![image](https://user-images.githubusercontent.com/42771836/177661842-5e4bb1de-7d97-4532-bdd7-a86761b9c736.png)
按照这个 添加 谢谢


> ![IMG_20220707_075333](https://user-images.githubusercontent.com/105803689/177661822-910548af-fa3a-48bd-bf7f-b9a1e714819d.png)

**Comment by Judp28** [comment]
已解决
