### ISSUE TITLE
有时打劫会报错list index out of range 

### ISSUE THREAD

**Issue by ZZZ-zero** [po-lan/zhenxun_plugins_TZseries#15]
如图
![~3BIU7P4P~1OPNU2B$(FS2I](https://user-images.githubusercontent.com/30883525/177715336-5a972d29-56df-454c-a8bb-f391ab90bbb1.png)

**Comment by po-lan** [comment]
这个报错可以忽略，
原因是 打劫的@是复制的 或者 没有@那个人
