### ISSUE TITLE
TZ21加载失败

### ISSUE THREAD

**Issue by ILYSHL** [po-lan/zhenxun_plugins_TZseries#17]
![$DVV`UCFQC A034J1}V(5W3](https://user-images.githubusercontent.com/42436917/178133101-9ad8f32d-b0b6-4598-b3be-a6611746312b.png)

全部文件均已下载，extensive_plugin中插件文件夹名为zhenxun_plugins_TZseries

**Comment by po-lan** [comment]
目前 21点为测试版，bug 会多一点

**Comment by po-lan** [comment]
这个问题修复了
再试一下吧
目前玩家庄 用不了
