### ISSUE TITLE
抢劫插件BUG(可能)及一些意见,

### ISSUE THREAD

**Issue by GverseFly** [po-lan/zhenxun_plugins_TZseries#18]
BUG(可能):
1.实测两个都有菜刀的用户抢劫时无法触发菜刀互砍（代码中有但是一直没见过触发）。
2.实测当一个用户同时持有电击枪和菜刀被抢劫时，100%不会被抢劫成功，不是标注的降低至20%,且消耗的是菜刀不是电击枪。
3.真寻BOT的配置文件(zhenxun_bot/configs/config.yaml)修改被监禁时长没有效果，去对应功能的.py文件修改后才有效果。
4.文件中有cd：300 的文本从来没被触发过
5.通过真寻插件仓库安装TZ插件且重启后查询插件仓库不会显示已经安装，但能够正常使用。
一些小建议：
1.希望能够在注释文本中增加道具在数据库中存储位置，防止群友烂买后无法清空。/增加超级用户指令可以指定清除某个用户的道具。
2.希望能够增加超级用户指令直接修改抢劫成功率和抢劫上限等操作。
2.希望除了抢劫以外大佬能开发一些金币其他用途；比如做个贵重物品的买卖插件一类。
![K6AM%YGPA3NSD_PZRY4K@CS](https://user-images.githubusercontent.com/106164618/178139373-6d441f94-34bd-4986-aef3-8d6c96dc8184.png)
![9@)X~DEV$CLD{Z$1OY%(SCE](https://user-images.githubusercontent.com/106164618/178139375-f8d35a2f-5bd6-47b1-ad3d-373e200cc659.png)

**Comment by po-lan** [comment]
emmm,
电击枪的部分 不是我自己写的，我找 写那个部分的人

**Comment by po-lan** [comment]
其他的部分我我看看

**Comment by po-lan** [comment]
日后 会 添加单日购买上限
现在 最新 的代码 有黑钱逻辑 ，黑钱的上限 会与 好感度相关 ，超过的部分 会被追回
成功率的 修改 可以说一下思路吗，目前我没什么思路，是直接增减还是什么？

**Comment by po-lan** [comment]
其他 金币玩法的话我 现在 打算写是 股票 和 彩票

目前 开发出来的插件 都是有原型的

打劫 21点 刮刮乐 基本都是群里原先的插件，不过 经过了 重构 或者其他的深度魔改

比如说 
  21点的流水控制 ，是基于 正常玩法的 让真寻 换底牌
  刮刮乐 是 按照 福利彩票刮刮乐 返奖 量写的
  乞讨是 基于 真寻给钱 魔改的，也是 这些插件 中税的 开端

**Comment by po-lan** [comment]
> > 日后 会 添加单日购买上限 现在 最新 的代码 有黑钱逻辑 ，黑钱的上限 会与 好感度相关 ，超过的部分 会被追回 成功率的 修改 可以说一下思路吗，目前我没什么思路，是直接增减还是什么？
> 
> 我个人是希望能够添加一些状态比如(兴奋，警惕)，或者花大量金币雇佣保镖，让抢劫/被抢劫的结果产生更多的结果。这样看起来会更有意思一些（写起来更难，仅供参考图一乐）。目前还是迫切需要超级用户指令来修改普通状态下/持有道具的(菜刀，电击枪)的抢劫/被抢劫成功率(直接增减)。如果抢劫cd等参数要是也能直接修改就更好了。

我也想 ，当时 那个Tstate 我根本不会用，所以说 抢劫 我也只能写成这样了
CD是 写的 按照真寻插件 写的，我不确定是否有接口可以直接更改，

你是指 管理员可以修改 道具 所影响的概率吗？，我限制的写法是随机

然后 电击枪的 我看了一下代码，那个人没有 对电击枪进行判断 所以说 就会很奇怪，电击枪他 是 直接 调用 的菜刀判断

**Comment by GverseFly** [comment]
> > > 日后 会 添加单日购买上限 现在 最新 的代码 有黑钱逻辑 ，黑钱的上限 会与 好感度相关 ，超过的部分 会被追回 成功率的 修改 可以说一下思路吗，目前我没什么思路，是直接增减还是什么？
> > 
> > 
> > 我个人是希望能够添加一些状态比如(兴奋，警惕)，或者花大量金币雇佣保镖，让抢劫/被抢劫的结果产生更多的结果。这样看起来会更有意思一些（写起来更难，仅供参考图一乐）。目前还是迫切需要超级用户指令来修改普通状态下/持有道具的(菜刀，电击枪)的抢劫/被抢劫成功率(直接增减)。如果抢劫cd等参数要是也能直接修改就更好了。
> 
> 我也想 ，当时 那个Tstate 我根本不会用，所以说 抢劫 我也只能写成这样了 CD是 写的 按照真寻插件 写的，我不确定是否有接口可以直接更改，
> 
> 你是指 管理员可以修改 道具 所影响的概率吗？，我限制的写法是随机
> 
> 然后 电击枪的 我看了一下代码，那个人没有 对电击枪进行判断 所以说 就会很奇怪，电击枪他 是 直接 调用 的菜刀判断
好吧，不过现在我那群人均百把菜刀(滥发金币的后果)，所以现急需要清理他们所买的道具，我现在不太清楚道具存储在数据库中哪个的位置上，能说一下吗，后续有没有机会添加超级用户指令来清除某个人或全体成员的道具仓库呢？

**Comment by shinianj** [comment]
> 

在baguser的表中

**Comment by shinianj** [comment]
> > > > 日后 会 添加单日购买上限 现在 最新 的代码 有黑钱逻辑 ，黑钱的上限 会与 好感度相关 ，超过的部分 会被追回 成功率的 修改 可以说一下思路吗，目前我没什么思路，是直接增减还是什么？
> > > 
> > > 
> > > 我个人是希望能够添加一些状态比如(兴奋，警惕)，或者花大量金币雇佣保镖，让抢劫/被抢劫的结果产生更多的结果。这样看起来会更有意思一些（写起来更难，仅供参考图一乐）。目前还是迫切需要超级用户指令来修改普通状态下/持有道具的(菜刀，电击枪)的抢劫/被抢劫成功率(直接增减)。如果抢劫cd等参数要是也能直接修改就更好了。
> > 
> > 
> > 我也想 ，当时 那个Tstate 我根本不会用，所以说 抢劫 我也只能写成这样了 CD是 写的 按照真寻插件 写的，我不确定是否有接口可以直接更改，
> > 你是指 管理员可以修改 道具 所影响的概率吗？，我限制的写法是随机
> > 然后 电击枪的 我看了一下代码，那个人没有 对电击枪进行判断 所以说 就会很奇怪，电击枪他 是 直接 调用 的菜刀判断
> > 好吧，不过现在我那群人均百把菜刀(滥发金币的后果)，所以现急需要清理他们所买的道具，我现在不太清楚道具存储在数据库中哪个的位置上，能说一下吗，后续有没有机会添加超级用户指令来清除某个人或全体成员的道具仓库呢？

在baguser的表中

**Comment by GverseFly** [comment]
> 

谢谢，这就去尝试修改。

**Comment by shinianj** [comment]
> BUG(可能): 1.实测两个都有菜刀的用户抢劫时无法触发菜刀互砍（代码中有但是一直没见过触发）。 2.实测当一个用户同时持有电击枪和菜刀被抢劫时，100%不会被抢劫成功，不是标注的降低至20%,且消耗的是菜刀不是电击枪。 3.真寻BOT的配置文件(zhenxun_bot/configs/config.yaml)修改被监禁时长没有效果，去对应功能的.py文件修改后才有效果。 4.文件中有cd：300 的文本从来没被触发过 5.通过真寻插件仓库安装TZ插件且重启后查询插件仓库不会显示已经安装，但能够正常使用。 一些小建议： 1.希望能够在注释文本中增加道具在数据库中存储位置，防止群友烂买后无法清空。/增加超级用户指令可以指定清除某个用户的道具。 2.希望能够增加超级用户指令直接修改抢劫成功率和抢劫上限等操作。 2.希望除了抢劫以外大佬能开发一些金币其他用途；比如做个贵重物品的买卖插件一类。 ![K6AM%YGPA3NSD_PZRY4K@CS](https://user-images.githubusercontent.com/106164618/178139373-6d441f94-34bd-4986-aef3-8d6c96dc8184.png) ![9@)X~DEV$CLD{Z$1OY%(SCE](https://user-images.githubusercontent.com/106164618/178139375-f8d35a2f-5bd6-47b1-ad3d-373e200cc659.png)

emmm关于电击枪没有删除这件事，确实是我在劫财的部分忘记添加代码删除道具了（光顾着写劫色了，劫财上面的部分没有修改），然后关于那个cd=300的，那个是劫色情况下才会发生的（你没有发出劫色相关的图我也不好说是不是我多此一举了）

**Comment by GverseFly** [comment]
> > BUG(可能): 1.实测两个都有菜刀的用户抢劫时无法触发菜刀互砍（代码中有但是一直没见过触发）。 2.实测当一个用户同时持有电击枪和菜刀被抢劫时，100%不会被抢劫成功，不是标注的降低至20%,且消耗的是菜刀不是电击枪。 3.真寻BOT的配置文件(zhenxun_bot/configs/config.yaml)修改被监禁时长没有效果，去对应功能的.py文件修改后才有效果。 4.文件中有cd：300 的文本从来没被触发过 5.通过真寻插件仓库安装TZ插件且重启后查询插件仓库不会显示已经安装，但能够正常使用。 一些小建议： 1.希望能够在注释文本中增加道具在数据库中存储位置，防止群友烂买后无法清空。/增加超级用户指令可以指定清除某个用户的道具。 2.希望能够增加超级用户指令直接修改抢劫成功率和抢劫上限等操作。 2.希望除了抢劫以外大佬能开发一些金币其他用途；比如做个贵重物品的买卖插件一类。 ![K6AM%YGPA3NSD_PZRY4K@CS](https://user-images.githubusercontent.com/106164618/178139373-6d441f94-34bd-4986-aef3-8d6c96dc8184.png) ![9@)X~DEV$CLD{Z$1OY%(SCE](https://user-images.githubusercontent.com/106164618/178139375-f8d35a2f-5bd6-47b1-ad3d-373e200cc659.png)
> 
> emmm关于电击枪没有删除这件事，确实是我在劫财的部分忘记添加代码删除道具了（光顾着写劫色了，劫财上面的部分没有修改），然后关于那个cd=300的，那个是劫色情况下才会发生的（你没有发出劫色相关的图我也不好说是不是我多此一举了）

我那沙雕群友确实很少执行劫色指令，所以我就基本没见过这段文本，所以比较好奇，辛苦大佬检查代码了。不过拼刀那段代码请一定要让它能够正常执行(我要看到血流成河.jpg)。谢谢大佬的解答。最后我还是希望能够在真寻帮助中能看到一些超级用户指令能够简化一些操作，在此先谢过二位大佬。

**Comment by po-lan** [comment]
拼刀的代码是成功率太低

**Comment by GverseFly** [comment]
> 拼刀的代码是成功率太低

那就好，那我先关闭 Issues 了

**Comment by po-lan** [comment]
打劫的部分写好了 
劫色的部分我没动，其他的概率 需要等他修改 
手动 替换一下 dajie吧

**Comment by GverseFly** [comment]
> 打劫的部分写好了 劫色的部分我没动，其他的概率 需要等他修改 手动 替换一下 dajie吧

好的
