### ISSUE TITLE
放插件目录里面了怎么没反应啊

### ISSUE THREAD

**Issue by AlanABCDE** [po-lan/zhenxun_plugins_TZseries#2]
装plugins目录里面了 启动的时候也提示成功导入了 但是输入指令以后也没反应啊

**Comment by po-lan** [comment]
> 装plugins目录里面了 启动的时候也提示成功导入了 但是输入指令以后也没反应啊

没报错的话 需要自己研究一下

**Comment by yanluoli** [comment]
打开__init__.py 看一下就明白了

**Comment by AlanABCDE** [comment]
> 

我是把插件放到自定义插件目录返回init.py里面的路径也改成当前这个目录了。还是没啥用，按照插件里面的指令调用机器人也是没反应，，，，寄了
![image](https://user-images.githubusercontent.com/65140019/175492498-e7a7196d-3100-4d58-9955-ec1b03c6bdd8.png)
![image](https://user-images.githubusercontent.com/65140019/175492544-6caf7f6b-1b81-4ce2-8401-294964257513.png)

**Comment by fuyang0811** [comment]
> > 
> 
> 我是把插件放到自定义插件目录的，然后init.py里面的路径也改成当前这个目录了。还是没啥用，按照插件里面的指令调用机器人也是没反应，，，，寄了 ![image](https://user-images.githubusercontent.com/65140019/175492498-e7a7196d-3100-4d58-9955-ec1b03c6bdd8.png) ![image](https://user-images.githubusercontent.com/65140019/175493225-747843fe-875e-43fd-9106-c0ea25b51d59.png)

我用的完整目录，没问题，重启后就可以用了。nonebot.load_plugins("/home/zhenxun_bot/plugins/zhenxun_plugins_TZseries")

**Comment by po-lan** [comment]
那为什么不试一下 ./plugins/zhenxun_plugins_TZseries
我认为这样也是OK的
