### ISSUE TITLE
关于21点好像有两个问题

### ISSUE THREAD

**Issue by 534019023** [po-lan/zhenxun_plugins_TZseries#20]
![image](https://user-images.githubusercontent.com/95991937/178405176-7932db34-171e-45af-b3e3-1b06db88957c.png)
一个是bot的牌会直接变成场上点数最高的玩家的牌，导致没有玩家能赢过bot
另一个是即使bot赢了也没有获得金币

**Comment by po-lan** [comment]
好的，我回一会去看看，
然后就是 这个 金库 和 21点没什么联动 ，21点的钱是存在内存的
不会存入金库 ，只有 税 会收入

**Comment by po-lan** [comment]
你看一下 你是什么时候下载的，机器人 牌 替换的问题 在两天前 应该是修复好了的

**Comment by 534019023** [comment]
谢谢回复
我就是刚刚下载的，显示的上次修改日期是7月11号下午四点

**Comment by po-lan** [comment]
> 谢谢回复 我就是刚刚下载的，显示的上次修改日期是7月11号下午四点

那我得好好看看代码了

**Comment by po-lan** [comment]
现在 应该修复了
你再试一下吧

**Comment by 534019023** [comment]
已经好了，非常感谢
还有我想问一下要怎么查看bot在21点里有多少钱，是否有个指令可以查看呢，或者能否和金库的钱进行统一呢

**Comment by po-lan** [comment]
emmmm
我并没有设计这部分 
21点的钱 主要目的是为了 防止 他们一直坑机器人 导致 群内金币过多的

**Comment by 534019023** [comment]
倒也是，是我没考虑那么多
