### ISSUE TITLE
21点结算时卡死

### ISSUE THREAD

**Issue by imxianyu21** [po-lan/zhenxun_plugins_TZseries#28]
rt，报错信息截图如下
![Screenshot_20220730-185337](https://user-images.githubusercontent.com/110275302/181908039-5a7e2972-fa4a-47fa-a5fb-33a3958bbdea.png)

**Comment by po-lan** [comment]
对应代码 已经找到了、正在找 解决办法
关闭流水控制就行

**Comment by imxianyu21** [comment]
好的

po-lan ***@***.***> 於 2022年8月3日 週三 22:28 寫道：

**Comment by po-lan** [comment]
临时修复了一下
