### ISSUE TITLE
#劫财后，打劫者没有得到钱

### ISSUE THREAD

**Issue by qclf** [po-lan/zhenxun_plugins_TZseries#31]
![QQ图片20221024143352](https://user-images.githubusercontent.com/97816993/197462381-8edd8144-bd0b-4997-b962-89cd1118a54a.png)
被打劫的钱有缺失，但是没有去到打劫者那边

**Comment by SanaeMio** [comment]
需要在CD之后发送 “#洗白” 命令，在24h内把黑钱洗白才能入账，不过洗白的时候也会有损失(
