### ISSUE TITLE
21点的一个bug

### ISSUE THREAD

**Issue by zzbo777** [po-lan/zhenxun_plugins_TZseries#34]
提一个21点的bug，玩家坐庄如果输了，只会从小真寻那里扣钱，没有扣庄家的钱。

**Comment by po-lan** [comment]
fix it at [the upload](https://github.com/po-lan/zhenxun_plugins_TZseries/commit/7ba7ffcb7ef1edfa228d9823b1b8bfefcc4b3c80)
