### ISSUE TITLE
怎么删除群成员的金币和存款？

### ISSUE THREAD

**Issue by CaffuChin0** [po-lan/zhenxun_plugins_TZseries#4]
有个群成员退群了但是在排行榜上还有他的数据

**Comment by po-lan** [comment]
> 有个群成员退群了但是在排行榜上还有他的数据

这需要进行数据库操作

**Comment by CaffuChin0** [comment]
> > 有个群成员退群了但是在排行榜上还有他的数据
> 
> 这需要进行数据库操作

okok谢谢，搞定了
