### ISSUE TITLE
扩展打劫功能的小建议

### ISSUE THREAD

**Issue by shinianj** [po-lan/zhenxun_plugins_TZseries#5]
希望打劫不仅仅是劫财，将指令扩充到#劫财、#劫色、#打劫道具，或许能够有更多的玩法，比如劫色可以让被劫色者在30分钟或者多长时间内的钱财归于劫色者，打劫道具会随机掉落他身上的道具（有些打劫之后全拿去买刀了，打劫他还没钱拿，这不比存银行离谱），还有希望刀子的储存能有个上限（不得不说刀子理财的这些人真的好会玩），当然以上只是建议（我知道您和弘涯改插件辛苦，实在不行还是把我close了吧）

**Comment by po-lan** [comment]
劫色的话 我真想不好怎么搞
但是 限量，这个要等阿咪改真寻的商店
最近我有点别的事
打劫 也是要加新的东西的

**Comment by po-lan** [comment]
有个问题是 都没钱了 
劫色 还是 会走金币 ，这不好吧
