### ISSUE TITLE
ValueError: non-integer arg 1 for randrange()

### ISSUE THREAD

**Issue by qwerdvd** [po-lan/zhenxun_plugins_TZseries#9]
![@Q5HY`TL7738BASPI3Q766T](https://user-images.githubusercontent.com/105906879/175990354-3beec70a-b4a9-471f-a021-66ef6447ef19.png)
晚上用的时候报错了
看了一下源码，python里面的除法默认是带小数的，//就是整除了
改了一下就好了
![WN7I3~FVOH8S~X4{8W@O6SN](https://user-images.githubusercontent.com/105906879/175990564-b9f1dd19-7b8a-4618-a7a5-9073c4f7ad75.png)

**Comment by po-lan** [comment]
这给和上个都是别人pr过来的
所以我也才知道有问题
